export const LOGIN = 'LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'

export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_SUCCESS_ACCOUNT = 'GET_SUCCESS_ACCOUNT'
export const ERROR_GET_ACCOUNT = 'ERROR_GET_ACCOUNT'

export const IS_AUTHENTICATE = 'IS_AUTHENTICATE'

export const CHANGE_ACСOUNT = 'CHANGE_ACСOUNT'

export const FILE_UPLOAD = 'FILE_UPLOAD'
export const ERROR_FILE_UPLOAD = 'ERROR_FILE_UPLOAD'

export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER'
export const ERROR_ACCOUNT_REGISTER = 'ERROR_ACCOUNT_REGISTER'
export const CLOSE_NOTIF_REGISTEER = 'CLOSE_NOTIF_REGISTEER'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const SUCCESS_FORGOT_PASSWORD = 'SUCCESS_FORGOT_PASSWORD'
export const ERROR_FORGOT_PASSWORD = 'ERROR_FORGOT_PASSWORD'

export const LOGOUT = 'LOGOUT'

export const SAVE_ACCOUNT = 'SAVE_ACCOUNT'
export const ERROR_SAVE_ACCOUNT = 'ERROR_SAVE_ACCOUNT'
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT'
export const RESTORE_ACCOUNT = 'RESTORE_ACCOUNT'
